services:
  postgres01:
    image: postgres:latest
    ports:
      - "53140:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb

  py-app:
    build: .
    depends_on:
      - postgres01
    env_file: .env
    command: ["python", "main.py", "sample-data.json"]
